server:
  port: 8080
  servlet:
    context-path: /douyin-video-crawler
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
API_URL: https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids={}&dytk={}